language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  app: fathomless-caverns-10433
  api_key:
    secure: QCu81nfUFkm2poX4qHPDwNAV65zwqatpuNUCTp8L+rWCb4g8ssTykFK4acLxCwX7h8EXPVstttu2V6pwK6kcEKxI7zlNfiXv3AWRBDQKjCAsafoAIxhhnSxT0HmTXeBNqeF1IDWKUa7TyNz1o8CN68Dz+X69WD+SXVigP3P+ju9SnhC30fh+ltTBXoA4m6i+jiyWzoBV3MS0a0vrB3q4PVuV4Qyl03VtC2+1L0hFx69QxUU0Pv6GsNBgyaoydsHTYLxxF7HUgLCI0yvXK0T5ZUS3lwsYYmqHQgfZn2CHAc3sXlpAeacXsqHkm94Z8i/wmg2bnRsgH7sSn2E47I6tZ5atyiXTgy+qdnuuzgFr4K9vU51paHQwCwz4BLZmnFW1abp9Z+8e3mRDS1GI2ZpANHRTM685aOF1gWbOhTnDbgomhloOIWCVbUun2IVyLqPSAMG4eqiKAfffCLZOmyC4zPxfEgUwkcTUvTHH04QPygSIvA41dMRdDi5N2EEHzupnG3sN8wCbPD8q/ceem1d9ZTpnJXVrUGIGN3y4FKlrpR7vM8ruNi1AIb4uuJ5YaM/RWl1aihk0dXxqmJDD4AqHW+y9k15XRPj4Nk+MjfuDypNJsnjhjSzVUUcWa3rV9loCWMDlUC6fH9/V0pH7UdmIwUnmceloPtksOPgXJFnH62M=
