language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  app: fathomless-caverns-10433
  api_key:
    secure: "CzFwD7qNIlr4ngnTxZVtDTO58gH4f+uKWxQCkhn7cbWdgoBcMgVJ6oqxodTGFJyPCG2+2VYGylpTJAKTpVEO8ysNAyH3rWBfoAnxRq8tm5uMQj2JFRrZSELg6rnEfkeVr3ylPxSv6FnxJWMKpCxOpt8MwKVXhZ/63YEPNE5Y100Ex0XwKc6r2TLR31X2oB3xa2RqhGBlctiPpOFtVensOAw/6wU9dqbKsWrQueQvDG62WYzsuEltKQ8gG/uHiD8gAiZlRBVt3va0MAfpLOZa7izt5sIkPpenpl/2W4vUbp7TI/2B1szuLaIFBOvHdRZnlhjeitXs/WiHVLWS1Un1J1498SqNwDWY+7kYRBkJ6WwpakoWFi5pX+W9NKkZtjZtuLRXwRa2peFQONKIuklzTrS1N9q8YN7dTslQognQ8q+5N8x7sN9BiUHvBXk16NKhjo/G/FSQniwclg4J7DyJbgbnLw60jvNdtqvObZZuy2k2vLtEBQKy+q+gAL/Wi35XNa+H+uFc8BolGwlUQMM5Cq4PEp5ovJXqr6mHSqoNSo9ey97kjMyKyBEdMCVoqRAjtgqFelpdif+TA0hRv8pnDTgtSOcxtidh8vBAgVGhScYFxnWz9rk+2EYDxLQRdf8iV/Vewxb+UMg5s6NTgl/C7SGEjCmekMTDIKaevxCgtbo=
