language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  app: fathomless-caverns-10433
  api_key:
    secure: hw4Doc1QZMyVvRlsd1isXRf5bG+vRL0PBskS5OA6fXx0IEhC934IDT+Mj+vNQNatMkeV2TH/JzaIz1u8shXcCzVAFwJgAoPsdBtOMCGk7z2nesyeCU4c7kEqVf6/uRYgsEwM9wQrGKikFeD27zsCXPeOcucLHSxY/W8VfZeJFRc5huuuR5JuwifE+2xMfOCxd/ttT/eFqxjKUqFgm3om8EFPE7HPjVFxMvY77Iie3PbTvAzK9QCIl/v1ew1EU/LAOFpoFULJFljxi+WEPfNgE9lfucG8Selo3nM2QvRq1Am177u2us95y+DcMU0ZqwPKVsaweKHmFh2RI7ToHkaZYkBOgv4WDlIiHWBaj+j5aQ+ZSB23RrKRAjlg2dI2C04z8w20CyjMezCq3dcagIhzoAQFjtavYA5u2KjDx+syaUB/ioXUilcYzKgQDaiilBXNot3isly8j/26YjD7aY8ve+r+Vw+s6W6bBiLmNVrHHlH/3bEu71YUHmY0jGbmbt/JZrcphyXIEq2iPmy7SG2FlD+cntu6/UsLUoNEGvyZ63w72EadoOzE9/+6va89BgvWLc7l6sUtHjkuYgNy+xOmEA6XFKYg1zxgp62LlfeqqitDRPcnrWYe0nFHNaXCoEaBtpNUfpWWazOyl6/ip5DwW1goXpNvBP503gXcKsFxLfk=
